version: '2'

services:

 onos:
  image: "cord/onos"
  ports:
   - "8101:8101" # ssh
   - "6653:6653" # OF
   - "8181:8181" # UI
  environment:
   ONOS_APPS: 'drivers,openflow-base'
  volumes:
   - "../onos-config/network-cfg.json:/root/onos/config/network-cfg.json"
